<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <PlatformTarget>x64</PlatformTarget>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OutputType>Library</OutputType>
    <RootNamespace>SightstealerColony</RootNamespace>
    <AssemblyName>SightstealerColony</AssemblyName>
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\..\..\RimWorldWin64_Data\Managed\Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Mods\HarmonyMod\Current\Assemblies\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="SightstealerConfigExtension.cs" />
    <Compile Include="SightstealerUtility.cs" />
    <Compile Include="Genes.cs" />
    <Compile Include="HediffComps.cs" />
    <Compile Include="ScenarioParts.cs" />
    <Compile Include="Abilities.cs" />
    <Compile Include="Rituals.cs" />
  </ItemGroup>
</Project>
